# This is a basic workflow to help you get started with Actions

name: merge-to-master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Stop Poshbot service
        run: net stop poshbot-master

      - name: Remove old module
        run: Remove-Item C:\poshbot\plugins\Poshbot.vSphere -Force -Confirm:$false -Recurse

      - name: copy new module
        run: cd .\PoshBot.vSphere\ && Copy-Item PoshBot.vSphere C:\poshbot\plugins\ -Recurse

      - name: Start Service
        run: net start poshbot-master




